sudo: false
language: scala
jdk:
  - openjdk7
  - oraclejdk8
scala:
   - 2.11.8
script:
#   - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
   - sbt ++$TRAVIS_SCALA_VERSION clean test 
after_success:
  - bash <(curl -s https://codecov.io/bash)