prefix : <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select ?x where { 
  #-- each node in the graph
  ?x :? ?x .

  { select ?x where {
	?x :a ?o .
	{ select ?x ?o where {
	   ?x :a ?o .
	   filter ( bound(?o) && ?o in (1, 2)) 
    } GROUP BY ?x ?o HAVING (COUNT(*)=1)
    }
  } GROUP BY ?x HAVING (COUNT(*)=1)
  }
  
  { select ?x where {
	?x :c ?o .
	{ select ?x ?o where {
	   ?x :c ?o .
	   filter ( bound(?o) && ?o in (3, 4)) 
    } GROUP BY ?x ?o HAVING (COUNT(*)=1)
    }
  } GROUP BY ?x HAVING (COUNT(*)=1)
  }
 
}