prefix : <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select ?x where { 
  #-- each node in the graph
  ?x :? ?x .

  { select ?x where {
	?x ?p1 [] .
	filter (  bound(?p1) && ?p1 in (:a, :b)) 
	{ select ?x where {
	   ?x ?p1 ?o1 .
	   filter ( bound(?o1) && ?o1 in (1, 2)) 
    } GROUP BY ?x HAVING (COUNT(*)=1)
    }
  } GROUP BY ?x HAVING (COUNT(*)=1)
  }

}