prefix : <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select ?x where { 
  #-- each node in the graph
  ?x :? ?x .

    { select ?x (count(*) as ?x_c0) where {
  	  ?x :a ?o .
	} GROUP BY ?x HAVING (COUNT(*)>=1)
	}
	{ select ?x (count(*) as ?x_c1) where {
	     ?x :a ?o .
	     filter ( bound(?o) && ?o in (1, 2, 3, 4)) 
      } GROUP BY ?x HAVING (COUNT(*)>=1)
    } 
	filter (?x_c0 = ?x_c1)
}