PREFIX :<http://example.org/>
construct {
 ?a :hasShape <a> 
} where {
{ SELECT ?a {
  ?a :a ?o .
 { SELECT ?a { ?a :a ?o . FILTER (?o = 1) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 2) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 3) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 4) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 5) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 6) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 7) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 8) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 9) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 10) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 11) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 12) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 13) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 14) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 15) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 16) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 17) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 18) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 19) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 20) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 21) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 22) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 23) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 24) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 25) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 26) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 27) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 28) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 29) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 30) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 31) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 32) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 33) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 34) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 35) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 36) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 37) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 38) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 39) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 40) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 41) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 42) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 43) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 44) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 45) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 46) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 47) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 48) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 49) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 50) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 51) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 52) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 53) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 54) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 55) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 56) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 57) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 58) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 59) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 60) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 61) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 62) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 63) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 64) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 65) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 66) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 67) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 68) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 69) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 70) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 71) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 72) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 73) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 74) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 75) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 76) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 77) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 78) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 79) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 80) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 81) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 82) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 83) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 84) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 85) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 86) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 87) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 88) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 89) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 90) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 91) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 92) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 93) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 94) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 95) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 96) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 97) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 98) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 99) } GROUP BY ?a HAVING (COUNT(*)=1) }
 { SELECT ?a { ?a :a ?o . FILTER (?o = 100) } GROUP BY ?a HAVING (COUNT(*)=1) }
} GROUP BY ?a HAVING (COUNT(*)=100)}
}