PREFIX :<http://example.org/>
CONSTRUCT { 
 ?a :hasShape :a 
} WHERE {
    { SELECT ?a {
      ?a :a ?o .
    } GROUP BY ?a HAVING (COUNT(*)=1)}
    { SELECT ?a {
      ?a :a ?o . FILTER ((?o = "1"^^<http://www.w3.org/2001/XMLSchema#integer>))
    } GROUP BY ?a HAVING (COUNT(*)=1)}
}